version: '3'

tasks:

  k3d:cluster:create:
    status:
      - k3d cluster get podcast-server
    cmds:
      - k3d cluster create podcast-server --port 80:80@loadbalancer --port 443:443@loadbalancer

  skaffold:dev:
    dir: ~/Workspace/gitlab.com/davinkevin/Podcast-Server
    env:
      SKAFFOLD: true
    deps:
      - task: k3d:cluster:create
    cmds:
      - skaffold dev --status-check=false

  database:start:
    env:
      DATABASE_PASSWORD: nAAdo5wNs7WEF1UxUobpJDfS9Si62PHa
      DATABASE_USERNAME: podcast-server-user
      DATABASE_NAME: podcast-server
    cmds:
      - docker run --rm
        -e POSTGRES_USER=$DATABASE_USERNAME
        -e POSTGRES_PASSWORD=$DATABASE_PASSWORD
        -e POSTGRES_DB=$DATABASE_NAME
        -p 5432:5432
        --name db-for-local-dev
        postgres:16.1-alpine

  release:
    env:
      CURRENT_VERSION: 2023.11.0
      NEW_VERSION: 2023.12.0
    cmds:
      - sd $CURRENT_VERSION $NEW_VERSION 
           backend/build.gradle.kts
           backend-lib-database/build.gradle.kts 
           backend-lib-youtubedl/build.gradle.kts
           build-logic/build-plugin-database/build.gradle.kts
           build-logic/build-plugin-docker-images/build.gradle.kts
           frontend-angular/build.gradle.kts
           frontend-angular/package.json
           frontend-angularjs/build.gradle.kts
           frontend-angularjs/npm-shrinkwrap.json
           frontend-angularjs/package.json
      - git cliff -t $NEW_VERSION > CHANGELOG.md
      - git add .
      - 'git ci -m "chore(release): release version $NEW_VERSION"'
      - 'git tag $NEW_VERSION -m "chore(release): release version $NEW_VERSION"'

  release:publish:
    env:
      PROJECT_ID: 13640563
      CI_SERVER_URL: https://gitlab.com
      CI_COMMIT_TAG:
        sh: git describe --abbrev=0
    cmds:
      - docker pull podcastserver/ui:$CI_COMMIT_TAG
      - docker pull podcastserver/backend:$CI_COMMIT_TAG
      - docker pull podcastserver/init-db:$CI_COMMIT_TAG
      - docker pull podcastserver/storage:$CI_COMMIT_TAG
      - UI_SHA=$(docker image inspect podcastserver/ui:$CI_COMMIT_TAG --format '{{ "{{" }} index (split (index .RepoDigests 0) ":") 1 {{ "}}" }}') &&
        BACKEND_SHA=$(docker image inspect podcastserver/backend:$CI_COMMIT_TAG --format '{{ "{{" }} index (split (index .RepoDigests 0) ":") 1 {{ "}}" }}') &&
        INIT_DB_SHA=$(docker image inspect podcastserver/init-db:$CI_COMMIT_TAG --format '{{ "{{" }} index (split (index .RepoDigests 0) ":") 1 {{ "}}" }}') &&
        STORAGE_SHA=$(docker image inspect podcastserver/storage:$CI_COMMIT_TAG --format '{{ "{{" }} index (split (index .RepoDigests 0) ":") 1 {{ "}}" }}') &&
        release-cli --project-id=$PROJECT_ID create
          --name $CI_COMMIT_TAG
          --description "$(git-cliff -l --strip all | tail -n +3)"
          --tag-name "$CI_COMMIT_TAG" --ref "$CI_COMMIT_TAG"
          --assets-link "{\"name\":\"ui\",\"url\":\"https://hub.docker.com/layers/podcastserver/ui/$CI_COMMIT_TAG/images/sha256-$UI_SHA\",\"link_type\":\"image\"}"
          --assets-link "{\"name\":\"backend\",\"url\":\"https://hub.docker.com/layers/podcastserver/backend/$CI_COMMIT_TAG/images/sha256-$BACKEND_SHA\",\"link_type\":\"image\"}"
          --assets-link "{\"name\":\"init-db\",\"url\":\"https://hub.docker.com/layers/podcastserver/init-db/$CI_COMMIT_TAG/images/sha256-$INIT_DB_SHA\",\"link_type\":\"image\"}"
          --assets-link "{\"name\":\"storage\",\"url\":\"https://hub.docker.com/layers/podcastserver/storage/$CI_COMMIT_TAG/images/sha256-$STORAGE_SHA\",\"link_type\":\"image\"}"

  push-to-github:
    env:
      GITLAB_DIRECTORY:
        sh: mktemp -d
    cmds:
      - |
        cd $GITLAB_DIRECTORY
        git clone --bare git@gitlab.com:davinkevin/Podcast-Server.git
        cd Podcast-Server.git
        git push --mirror --repo git@github.com:davinkevin/Podcast-Server.git


  update:flyway:
    cmds:
      - git fetch
      - git rb origin/renovate/org.flywaydb-flyway-database-postgresql-10.x
      - git rb origin/renovate/flyway-flyway-10.x
      - git rb origin/renovate/org.flywaydb.flyway-10.x
      - git rb origin/main