apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: console
spec:
  rules:
    - matches:
        - path:
            value: "/"
      backendRefs:
        - name: storage
          port: 9001