apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - podcast-server
  - minio

patches:
  - path: certs/add-tls.yaml
    target:
      kind: Ingress
      version: v1
      group: networking.k8s.io

configMapGenerator:
  - name: ingress
    literals:
      - podcast=podcast.k8s.local
      - minio=minio.podcast.k8s.local
      - bucket=dev-podcasts

secretGenerator:
  - name: certificates-k8s-local
    files:
      - certs/tls.crt
      - certs/tls.key
    type: kubernetes.io/tls

replacements:
  - source:
      kind: Secret
      name: certificates-k8s-local
      fieldPath: metadata.name
    targets:
      - select:
          kind: Ingress
        fieldPaths:
          - spec.tls.0.secretName
        options:
          create: true
  - source:
      kind: ConfigMap
      name: ingress
      fieldPath: data.podcast
    targets:
      - select:
          kind: Ingress
          name: podcast-server
        fieldPaths:
          - spec.rules.0.host
          - spec.tls.0.hosts.0
        options:
          create: true
  - source:
      kind: ConfigMap
      name: ingress
      fieldPath: data.bucket
    targets:
      - select:
          kind: Ingress
          name: podcast-server
        fieldPaths:
          - spec.rules.0.http.paths.2.path
        options:
          delimiter: "/"
          index: 1
  - source:
      kind: ConfigMap
      name: ingress
      fieldPath: data.minio
    targets:
      - select:
          kind: Ingress
          name: minio-console
        fieldPaths:
          - spec.rules.0.host
          - spec.tls.0.hosts.0
        options:
          create: true


