[general]

host = "::"
port = 8080
root = "/podcast-server"
log-level = "error"

page-fallback = "/podcast-server/index.html"
cache-control-headers = true
compression = true
compression-static = true
security-headers = true
directory-listing = false
redirect-trailing-slash = true
ignore-hidden-files = true
