apiVersion: batch/v1
kind: Job
metadata:
  name: init-db
spec:
  backoffLimit: 6
  ttlSecondsAfterFinished: 60
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: init-db
          image: podcastserver/init-db
          env:
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: database
                  key: name
            - name: DATABASE_SERVICE_NAME
              value: database
            - name: FLYWAY_URL
              value: jdbc:postgresql://$(DATABASE_SERVICE_NAME):5432/$(DATABASE_NAME)
            - name: FLYWAY_USER
              valueFrom:
                configMapKeyRef:
                  name: database
                  key: username
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database
                  key: password
            - name: FLYWAY_CONNECT_RETRIES
              value: "30"
