UPDATE COVER SET URL='https://via.placeholder.com/200x200' WHERE URL IS NULL;
ALTER TABLE COVER
    ALTER COLUMN URL SET NOT NULL,
    ALTER COLUMN URL SET DEFAULT 'https://via.placeholder.com/200x200';

UPDATE COVER SET HEIGHT = 200 WHERE HEIGHT IS NULL;
ALTER TABLE COVER
    ALTER COLUMN HEIGHT SET NOT NULL,
    ALTER COLUMN HEIGHT SET DEFAULT 200;

UPDATE COVER SET WIDTH = 200 WHERE WIDTH IS NULL;
ALTER TABLE COVER
    ALTER COLUMN WIDTH SET NOT NULL,
    ALTER COLUMN WIDTH SET DEFAULT 200;
