CREATE TYPE DOWNLOADING_STATE AS ENUM ('WAITING', 'DOWNLOADING');

CREATE TABLE DOWNLOADING_ITEM (
    ITEM_ID UUID NOT NULL,
    POSITION INT NOT NULL,
    STATE DOWNLOADING_STATE NOT NULL DEFAULT 'WAITING',

    PRIMARY KEY(ITEM_ID),
    FOREIGN KEY(ITEM_ID) REFERENCES ITEM(ID),
    UNIQUE (POSITION) DEFERRABLE INITIALLY DEFERRED
)
