ALTER TABLE ITEM
    ADD COLUMN GUID TEXT,
    DROP CONSTRAINT item_podcast_id_url_key
;

UPDATE ITEM SET GUID=COALESCE(ITEM.URL, ITEM.ID::text);

ALTER TABLE ITEM
    ADD CONSTRAINT ITEM_WITH_GUID_IS_UNIQUE_IN_PODCAST UNIQUE (GUID, PODCAST_ID),
    ALTER COLUMN GUID SET NOT NULL;
