/*
 * This file is generated by jOOQ.
 */
package com.github.davinkevin.podcastserver.database;


import com.github.davinkevin.podcastserver.database.tables.FlywaySchemaHistory;
import com.github.davinkevin.podcastserver.database.tables.Item;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex(DSL.name("flyway_schema_history_s_idx"), FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
    public static final Index ITEM_DOWNLOAD_DATE_ASC = Internal.createIndex(DSL.name("item_download_date_asc"), Item.ITEM, new OrderField[] { Item.ITEM.DOWNLOAD_DATE }, false);
    public static final Index ITEM_DOWNLOAD_DATE_DESC = Internal.createIndex(DSL.name("item_download_date_desc"), Item.ITEM, new OrderField[] { Item.ITEM.DOWNLOAD_DATE.desc() }, false);
    public static final Index ITEM_PUB_DATE_ASC = Internal.createIndex(DSL.name("item_pub_date_asc"), Item.ITEM, new OrderField[] { Item.ITEM.PUB_DATE }, false);
    public static final Index ITEM_PUB_DATE_DESC = Internal.createIndex(DSL.name("item_pub_date_desc"), Item.ITEM, new OrderField[] { Item.ITEM.PUB_DATE.desc() }, false);
    public static final Index ITEM_TITLE = Internal.createIndex(DSL.name("item_title"), Item.ITEM, new OrderField[] { Item.ITEM.TITLE }, false);
}
