apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: backend
      spec:
        template:
          spec:
            containers:
              - name: app
                image: podcastserver/backend
                env:
                - name: JAVA_TOOL_OPTIONS
                  value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
                ports:
                - name: remote-debug
                  containerPort: 5005
                  protocol: TCP
