apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: storage
spec:
  rules:
    - matches:
        - path:
            value: "/dev-podcasts"
      backendRefs:
        - name: storage
          port: 9000