apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: podcast-server

resources:
  - ../all-in-one

components:
  - ../../base/components/namespace
  - ingress

patchesStrategicMerge:
  - volume.yaml

configMapGenerator:
  - name: storage
    behavior: merge
    literals:
      - bucket=dev-podcasts

secretGenerator:
  - name: database
    behavior: merge
    literals:
      - password=nAAdo5wNs7WEF1UxUobpJDfS9Si62PHa
  - name: podcast-server
    behavior: merge
    literals:
      - api.youtube=TO_BE_DEFINED
    type: Opaque
  - name: storage
    behavior: merge
    literals:
      - password=Mns1G6RgPtLgy68H
