
CREATE USER IF NOT EXISTS SA SALT '8e3319b3beee622c' HASH '7a727ab356a4428e19e6e72718a09f48436e0038e2f18b27efa8873a58388135' ADMIN;

CREATE CACHED TABLE IF NOT EXISTS PUBLIC.COVER(
    ID UUID NOT NULL,
    HEIGHT INTEGER,
    URL VARCHAR(255),
    WIDTH INTEGER,

    PRIMARY KEY(ID)
);

CREATE CACHED TABLE IF NOT EXISTS PUBLIC.TAG(
    ID UUID NOT NULL,
    NAME VARCHAR(255),

    PRIMARY KEY(ID),
    UNIQUE(NAME)
);

CREATE CACHED TABLE PUBLIC.PODCAST(
    ID UUID NOT NULL,
    DESCRIPTION VARCHAR(65535),
    HAS_TO_BE_DELETED BOOLEAN,
    LAST_UPDATE TIMESTAMP,
    SIGNATURE VARCHAR(255),
    TITLE VARCHAR(255),
    TYPE VARCHAR(255),
    URL VARCHAR(65535),
    COVER_ID UUID,

    PRIMARY KEY(ID),
    FOREIGN KEY(COVER_ID) REFERENCES PUBLIC.COVER(ID),
);

CREATE CACHED TABLE IF NOT EXISTS PUBLIC.ITEM(
    ID UUID NOT NULL,
    CREATION_DATE TIMESTAMP,
    DESCRIPTION VARCHAR(2147483647),
    DOWNLOAD_DATE TIMESTAMP,
    FILE_NAME VARCHAR(255),
    LENGTH BIGINT,
    MIME_TYPE VARCHAR(255),
    NUMBER_OF_FAIL INTEGER,
    PUB_DATE TIMESTAMP,
    STATUS VARCHAR(255),
    TITLE VARCHAR(254) NOT NULL,
    URL VARCHAR(65535),
    COVER_ID UUID,
    PODCAST_ID UUID,

    PRIMARY KEY(ID),
    FOREIGN KEY(PODCAST_ID) REFERENCES PUBLIC.PODCAST(ID),
    FOREIGN KEY(COVER_ID) REFERENCES PUBLIC.COVER(ID),
    UNIQUE(PODCAST_ID, URL)
);

CREATE CACHED TABLE IF NOT EXISTS PUBLIC.PODCAST_TAGS(
    PODCASTS_ID UUID NOT NULL,
    TAGS_ID UUID NOT NULL,

    PRIMARY KEY(PODCASTS_ID, TAGS_ID),
    FOREIGN KEY(TAGS_ID) REFERENCES PUBLIC.TAG(ID),
    FOREIGN KEY(PODCASTS_ID) REFERENCES PUBLIC.PODCAST(ID)
);

CREATE CACHED TABLE IF NOT EXISTS PUBLIC.WATCH_LIST(
    ID UUID NOT NULL,
    NAME VARCHAR(255),

    PRIMARY KEY(ID)
);          

CREATE CACHED TABLE IF NOT EXISTS PUBLIC.WATCH_LIST_ITEMS(
    WATCH_LISTS_ID UUID NOT NULL,
    ITEMS_ID UUID NOT NULL,

    PRIMARY KEY(WATCH_LISTS_ID, ITEMS_ID),
    FOREIGN KEY(ITEMS_ID) REFERENCES PUBLIC.ITEM(ID),
    FOREIGN KEY(WATCH_LISTS_ID) REFERENCES PUBLIC.WATCH_LIST(ID)
);

CREATE INDEX IF NOT EXISTS PUBLIC.ITEM_PUB_DATE_DESC ON PUBLIC.ITEM(PUB_DATE DESC);
CREATE INDEX IF NOT EXISTS PUBLIC.ITEM_PUB_DATE_ASC ON PUBLIC.ITEM(PUB_DATE);
CREATE INDEX IF NOT EXISTS PUBLIC.ITEM_DOWNLOAD_DATE_ASC ON PUBLIC.ITEM(DOWNLOAD_DATE);
CREATE INDEX IF NOT EXISTS PUBLIC.ITEM_DOWNLOAD_DATE_DESC ON PUBLIC.ITEM(DOWNLOAD_DATE DESC);