;              
CREATE USER IF NOT EXISTS SA SALT '8e3319b3beee622c' HASH '7a727ab356a4428e19e6e72718a09f48436e0038e2f18b27efa8873a58388135' ADMIN;            
CREATE CACHED TABLE PUBLIC.COVER(
    ID UUID NOT NULL,
    HEIGHT INTEGER,
    URL VARCHAR(255),
    WIDTH INTEGER
);         
ALTER TABLE PUBLIC.COVER ADD CONSTRAINT PUBLIC.CONSTRAINT_3 PRIMARY KEY(ID);   
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.COVER;    
CREATE CACHED TABLE PUBLIC.ITEM(
    ID UUID NOT NULL,
    CREATION_DATE TIMESTAMP,
    DESCRIPTION VARCHAR(2147483647),
    DOWNLOAD_DATE TIMESTAMP,
    FILE_NAME VARCHAR(255),
    LENGTH BIGINT,
    MIME_TYPE VARCHAR(255),
    NUMBER_OF_FAIL INTEGER,
    PUB_DATE TIMESTAMP,
    STATUS VARCHAR(255),
    TITLE VARCHAR(254) NOT NULL,
    URL VARCHAR(65535),
    COVER_ID UUID,
    PODCAST_ID UUID
);               
ALTER TABLE PUBLIC.ITEM ADD CONSTRAINT PUBLIC.CONSTRAINT_2 PRIMARY KEY(ID);    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ITEM;     
CREATE CACHED TABLE PUBLIC.PODCAST(
    ID UUID NOT NULL,
    DESCRIPTION VARCHAR(65535),
    HAS_TO_BE_DELETED BOOLEAN,
    LAST_UPDATE TIMESTAMP,
    SIGNATURE VARCHAR(255),
    TITLE VARCHAR(255),
    TYPE VARCHAR(255),
    URL VARCHAR(65535),
    COVER_ID UUID
);    
ALTER TABLE PUBLIC.PODCAST ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(ID); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PODCAST;  
CREATE CACHED TABLE PUBLIC.PODCAST_TAGS(
    PODCASTS_ID UUID NOT NULL,
    TAGS_ID UUID NOT NULL
);           
ALTER TABLE PUBLIC.PODCAST_TAGS ADD CONSTRAINT PUBLIC.CONSTRAINT_27 PRIMARY KEY(PODCASTS_ID, TAGS_ID);         
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PODCAST_TAGS;             
CREATE CACHED TABLE PUBLIC.TAG(
    ID UUID NOT NULL,
    NAME VARCHAR(255)
); 
ALTER TABLE PUBLIC.TAG ADD CONSTRAINT PUBLIC.CONSTRAINT_14 PRIMARY KEY(ID);    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TAG;      
CREATE CACHED TABLE PUBLIC.WATCH_LIST(
    ID UUID NOT NULL,
    NAME VARCHAR(255)
);          
ALTER TABLE PUBLIC.WATCH_LIST ADD CONSTRAINT PUBLIC.CONSTRAINT_18 PRIMARY KEY(ID);             
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.WATCH_LIST;               
CREATE CACHED TABLE PUBLIC.WATCH_LIST_ITEMS(
    WATCH_LISTS_ID UUID NOT NULL,
    ITEMS_ID UUID NOT NULL
);   
ALTER TABLE PUBLIC.WATCH_LIST_ITEMS ADD CONSTRAINT PUBLIC.CONSTRAINT_E PRIMARY KEY(WATCH_LISTS_ID, ITEMS_ID);  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.WATCH_LIST_ITEMS;         
ALTER TABLE PUBLIC.TAG ADD CONSTRAINT PUBLIC.UK_1WDPSED5KNA2Y38HNBGRNHI5B UNIQUE(NAME);        
ALTER TABLE PUBLIC.ITEM ADD CONSTRAINT PUBLIC.UKAHJEQ7CQ2MI7YJG296G727QRG UNIQUE(PODCAST_ID, URL);             
ALTER TABLE PUBLIC.PODCAST_TAGS ADD CONSTRAINT PUBLIC.FK1THYJTDCSLWVX7VRSCPLWSVOQ FOREIGN KEY(TAGS_ID) REFERENCES PUBLIC.TAG(ID) NOCHECK;      
ALTER TABLE PUBLIC.WATCH_LIST_ITEMS ADD CONSTRAINT PUBLIC.FKICJX1R5YBAYC23B7VXAHX5CCI FOREIGN KEY(ITEMS_ID) REFERENCES PUBLIC.ITEM(ID) NOCHECK;
ALTER TABLE PUBLIC.WATCH_LIST_ITEMS ADD CONSTRAINT PUBLIC.FKK9KXUMXX6UEL80GU1PG6MV9RC FOREIGN KEY(WATCH_LISTS_ID) REFERENCES PUBLIC.WATCH_LIST(ID) NOCHECK;    
ALTER TABLE PUBLIC.PODCAST_TAGS ADD CONSTRAINT PUBLIC.FKRJU4X129X9UR3T0MESSDTB5C2 FOREIGN KEY(PODCASTS_ID) REFERENCES PUBLIC.PODCAST(ID) NOCHECK;              
ALTER TABLE PUBLIC.ITEM ADD CONSTRAINT PUBLIC.FKFJPRLDM3BWN74787B87TT1MA1 FOREIGN KEY(PODCAST_ID) REFERENCES PUBLIC.PODCAST(ID) NOCHECK;       
ALTER TABLE PUBLIC.PODCAST ADD CONSTRAINT PUBLIC.FK2GX3UYNWOHASY0E5T85MG2HJE FOREIGN KEY(COVER_ID) REFERENCES PUBLIC.COVER(ID) NOCHECK;        
ALTER TABLE PUBLIC.ITEM ADD CONSTRAINT PUBLIC.FKHNXBML4NEQMU3O7AHXNOQJDIV FOREIGN KEY(COVER_ID) REFERENCES PUBLIC.COVER(ID) NOCHECK;           
