/*
 * This file is generated by jOOQ.
 */
package com.github.davinkevin.podcastserver.database.tables.records;


import com.github.davinkevin.podcastserver.database.tables.ApplicationSettings;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ApplicationSettingsRecord extends UpdatableRecordImpl<ApplicationSettingsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.application_settings.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.application_settings.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.application_settings.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.application_settings.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(1);
    }

    /**
     * Setter for <code>public.application_settings.concurrent_download</code>.
     */
    public void setConcurrentDownload(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.application_settings.concurrent_download</code>.
     */
    public Integer getConcurrentDownload() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.application_settings.number_of_try</code>.
     */
    public void setNumberOfTry(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.application_settings.number_of_try</code>.
     */
    public Integer getNumberOfTry() {
        return (Integer) get(3);
    }

    /**
     * Setter for
     * <code>public.application_settings.number_of_day_to_download</code>.
     */
    public void setNumberOfDayToDownload(Long value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>public.application_settings.number_of_day_to_download</code>.
     */
    public Long getNumberOfDayToDownload() {
        return (Long) get(4);
    }

    /**
     * Setter for
     * <code>public.application_settings.number_of_day_to_save_cover</code>.
     */
    public void setNumberOfDayToSaveCover(Long value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>public.application_settings.number_of_day_to_save_cover</code>.
     */
    public Long getNumberOfDayToSaveCover() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ApplicationSettingsRecord
     */
    public ApplicationSettingsRecord() {
        super(ApplicationSettings.APPLICATION_SETTINGS);
    }

    /**
     * Create a detached, initialised ApplicationSettingsRecord
     */
    public ApplicationSettingsRecord(UUID id, OffsetDateTime createdAt, Integer concurrentDownload, Integer numberOfTry, Long numberOfDayToDownload, Long numberOfDayToSaveCover) {
        super(ApplicationSettings.APPLICATION_SETTINGS);

        setId(id);
        setCreatedAt(createdAt);
        setConcurrentDownload(concurrentDownload);
        setNumberOfTry(numberOfTry);
        setNumberOfDayToDownload(numberOfDayToDownload);
        setNumberOfDayToSaveCover(numberOfDayToSaveCover);
        resetChangedOnNotNull();
    }
}
