/*
 * This file is generated by jOOQ.
 */
package com.github.davinkevin.podcastserver.database.tables.records;


import com.github.davinkevin.podcastserver.database.enums.DownloadingState;
import com.github.davinkevin.podcastserver.database.tables.DownloadingItem;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DownloadingItemRecord extends UpdatableRecordImpl<DownloadingItemRecord> implements Record3<UUID, Integer, DownloadingState> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.downloading_item.item_id</code>.
     */
    public void setItemId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.downloading_item.item_id</code>.
     */
    public UUID getItemId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.downloading_item.position</code>.
     */
    public void setPosition(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.downloading_item.position</code>.
     */
    public Integer getPosition() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.downloading_item.state</code>.
     */
    public void setState(DownloadingState value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.downloading_item.state</code>.
     */
    public DownloadingState getState() {
        return (DownloadingState) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, Integer, DownloadingState> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<UUID, Integer, DownloadingState> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return DownloadingItem.DOWNLOADING_ITEM.ITEM_ID;
    }

    @Override
    public Field<Integer> field2() {
        return DownloadingItem.DOWNLOADING_ITEM.POSITION;
    }

    @Override
    public Field<DownloadingState> field3() {
        return DownloadingItem.DOWNLOADING_ITEM.STATE;
    }

    @Override
    public UUID component1() {
        return getItemId();
    }

    @Override
    public Integer component2() {
        return getPosition();
    }

    @Override
    public DownloadingState component3() {
        return getState();
    }

    @Override
    public UUID value1() {
        return getItemId();
    }

    @Override
    public Integer value2() {
        return getPosition();
    }

    @Override
    public DownloadingState value3() {
        return getState();
    }

    @Override
    public DownloadingItemRecord value1(UUID value) {
        setItemId(value);
        return this;
    }

    @Override
    public DownloadingItemRecord value2(Integer value) {
        setPosition(value);
        return this;
    }

    @Override
    public DownloadingItemRecord value3(DownloadingState value) {
        setState(value);
        return this;
    }

    @Override
    public DownloadingItemRecord values(UUID value1, Integer value2, DownloadingState value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DownloadingItemRecord
     */
    public DownloadingItemRecord() {
        super(DownloadingItem.DOWNLOADING_ITEM);
    }

    /**
     * Create a detached, initialised DownloadingItemRecord
     */
    public DownloadingItemRecord(UUID itemId, Integer position, DownloadingState state) {
        super(DownloadingItem.DOWNLOADING_ITEM);

        setItemId(itemId);
        setPosition(position);
        setState(state);
        resetChangedOnNotNull();
    }
}
