/*
 * This file is generated by jOOQ.
 */
package com.github.davinkevin.podcastserver.database.tables.records;


import com.github.davinkevin.podcastserver.database.enums.ItemStatus;
import com.github.davinkevin.podcastserver.database.tables.Item;

import java.nio.file.Path;
import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ItemRecord extends UpdatableRecordImpl<ItemRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.item.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.item.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.item.creation_date</code>.
     */
    public void setCreationDate(OffsetDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.item.creation_date</code>.
     */
    public OffsetDateTime getCreationDate() {
        return (OffsetDateTime) get(1);
    }

    /**
     * Setter for <code>public.item.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.item.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.item.download_date</code>.
     */
    public void setDownloadDate(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.item.download_date</code>.
     */
    public OffsetDateTime getDownloadDate() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.item.file_name</code>.
     */
    public void setFileName(Path value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.item.file_name</code>.
     */
    public Path getFileName() {
        return (Path) get(4);
    }

    /**
     * Setter for <code>public.item.length</code>.
     */
    public void setLength(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.item.length</code>.
     */
    public Long getLength() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.item.mime_type</code>.
     */
    public void setMimeType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.item.mime_type</code>.
     */
    public String getMimeType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.item.number_of_fail</code>.
     */
    public void setNumberOfFail(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.item.number_of_fail</code>.
     */
    public Integer getNumberOfFail() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.item.pub_date</code>.
     */
    public void setPubDate(OffsetDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.item.pub_date</code>.
     */
    public OffsetDateTime getPubDate() {
        return (OffsetDateTime) get(8);
    }

    /**
     * Setter for <code>public.item.title</code>.
     */
    public void setTitle(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.item.title</code>.
     */
    public String getTitle() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.item.url</code>.
     */
    public void setUrl(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.item.url</code>.
     */
    public String getUrl() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.item.cover_id</code>.
     */
    public void setCoverId(UUID value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.item.cover_id</code>.
     */
    public UUID getCoverId() {
        return (UUID) get(11);
    }

    /**
     * Setter for <code>public.item.podcast_id</code>.
     */
    public void setPodcastId(UUID value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.item.podcast_id</code>.
     */
    public UUID getPodcastId() {
        return (UUID) get(12);
    }

    /**
     * Setter for <code>public.item.guid</code>.
     */
    public void setGuid(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.item.guid</code>.
     */
    public String getGuid() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.item.status</code>.
     */
    public void setStatus(ItemStatus value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.item.status</code>.
     */
    public ItemStatus getStatus() {
        return (ItemStatus) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ItemRecord
     */
    public ItemRecord() {
        super(Item.ITEM);
    }

    /**
     * Create a detached, initialised ItemRecord
     */
    public ItemRecord(UUID id, OffsetDateTime creationDate, String description, OffsetDateTime downloadDate, Path fileName, Long length, String mimeType, Integer numberOfFail, OffsetDateTime pubDate, String title, String url, UUID coverId, UUID podcastId, String guid, ItemStatus status) {
        super(Item.ITEM);

        setId(id);
        setCreationDate(creationDate);
        setDescription(description);
        setDownloadDate(downloadDate);
        setFileName(fileName);
        setLength(length);
        setMimeType(mimeType);
        setNumberOfFail(numberOfFail);
        setPubDate(pubDate);
        setTitle(title);
        setUrl(url);
        setCoverId(coverId);
        setPodcastId(podcastId);
        setGuid(guid);
        setStatus(status);
        resetChangedOnNotNull();
    }
}
