/*
 * This file is generated by jOOQ.
 */
package com.github.davinkevin.podcastserver.database.tables.records;


import com.github.davinkevin.podcastserver.database.enums.ItemStatus;
import com.github.davinkevin.podcastserver.database.tables.Item;

import java.nio.file.Path;
import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemRecord extends UpdatableRecordImpl<ItemRecord> implements Record15<UUID, OffsetDateTime, String, OffsetDateTime, Path, Long, String, Integer, OffsetDateTime, String, String, UUID, UUID, String, ItemStatus> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.item.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.item.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.item.creation_date</code>.
     */
    public void setCreationDate(OffsetDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.item.creation_date</code>.
     */
    public OffsetDateTime getCreationDate() {
        return (OffsetDateTime) get(1);
    }

    /**
     * Setter for <code>public.item.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.item.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.item.download_date</code>.
     */
    public void setDownloadDate(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.item.download_date</code>.
     */
    public OffsetDateTime getDownloadDate() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.item.file_name</code>.
     */
    public void setFileName(Path value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.item.file_name</code>.
     */
    public Path getFileName() {
        return (Path) get(4);
    }

    /**
     * Setter for <code>public.item.length</code>.
     */
    public void setLength(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.item.length</code>.
     */
    public Long getLength() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.item.mime_type</code>.
     */
    public void setMimeType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.item.mime_type</code>.
     */
    public String getMimeType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.item.number_of_fail</code>.
     */
    public void setNumberOfFail(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.item.number_of_fail</code>.
     */
    public Integer getNumberOfFail() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.item.pub_date</code>.
     */
    public void setPubDate(OffsetDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.item.pub_date</code>.
     */
    public OffsetDateTime getPubDate() {
        return (OffsetDateTime) get(8);
    }

    /**
     * Setter for <code>public.item.title</code>.
     */
    public void setTitle(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.item.title</code>.
     */
    public String getTitle() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.item.url</code>.
     */
    public void setUrl(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.item.url</code>.
     */
    public String getUrl() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.item.cover_id</code>.
     */
    public void setCoverId(UUID value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.item.cover_id</code>.
     */
    public UUID getCoverId() {
        return (UUID) get(11);
    }

    /**
     * Setter for <code>public.item.podcast_id</code>.
     */
    public void setPodcastId(UUID value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.item.podcast_id</code>.
     */
    public UUID getPodcastId() {
        return (UUID) get(12);
    }

    /**
     * Setter for <code>public.item.guid</code>.
     */
    public void setGuid(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.item.guid</code>.
     */
    public String getGuid() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.item.status</code>.
     */
    public void setStatus(ItemStatus value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.item.status</code>.
     */
    public ItemStatus getStatus() {
        return (ItemStatus) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row15<UUID, OffsetDateTime, String, OffsetDateTime, Path, Long, String, Integer, OffsetDateTime, String, String, UUID, UUID, String, ItemStatus> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    @Override
    public Row15<UUID, OffsetDateTime, String, OffsetDateTime, Path, Long, String, Integer, OffsetDateTime, String, String, UUID, UUID, String, ItemStatus> valuesRow() {
        return (Row15) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Item.ITEM.ID;
    }

    @Override
    public Field<OffsetDateTime> field2() {
        return Item.ITEM.CREATION_DATE;
    }

    @Override
    public Field<String> field3() {
        return Item.ITEM.DESCRIPTION;
    }

    @Override
    public Field<OffsetDateTime> field4() {
        return Item.ITEM.DOWNLOAD_DATE;
    }

    @Override
    public Field<Path> field5() {
        return Item.ITEM.FILE_NAME;
    }

    @Override
    public Field<Long> field6() {
        return Item.ITEM.LENGTH;
    }

    @Override
    public Field<String> field7() {
        return Item.ITEM.MIME_TYPE;
    }

    @Override
    public Field<Integer> field8() {
        return Item.ITEM.NUMBER_OF_FAIL;
    }

    @Override
    public Field<OffsetDateTime> field9() {
        return Item.ITEM.PUB_DATE;
    }

    @Override
    public Field<String> field10() {
        return Item.ITEM.TITLE;
    }

    @Override
    public Field<String> field11() {
        return Item.ITEM.URL;
    }

    @Override
    public Field<UUID> field12() {
        return Item.ITEM.COVER_ID;
    }

    @Override
    public Field<UUID> field13() {
        return Item.ITEM.PODCAST_ID;
    }

    @Override
    public Field<String> field14() {
        return Item.ITEM.GUID;
    }

    @Override
    public Field<ItemStatus> field15() {
        return Item.ITEM.STATUS;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public OffsetDateTime component2() {
        return getCreationDate();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public OffsetDateTime component4() {
        return getDownloadDate();
    }

    @Override
    public Path component5() {
        return getFileName();
    }

    @Override
    public Long component6() {
        return getLength();
    }

    @Override
    public String component7() {
        return getMimeType();
    }

    @Override
    public Integer component8() {
        return getNumberOfFail();
    }

    @Override
    public OffsetDateTime component9() {
        return getPubDate();
    }

    @Override
    public String component10() {
        return getTitle();
    }

    @Override
    public String component11() {
        return getUrl();
    }

    @Override
    public UUID component12() {
        return getCoverId();
    }

    @Override
    public UUID component13() {
        return getPodcastId();
    }

    @Override
    public String component14() {
        return getGuid();
    }

    @Override
    public ItemStatus component15() {
        return getStatus();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public OffsetDateTime value2() {
        return getCreationDate();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public OffsetDateTime value4() {
        return getDownloadDate();
    }

    @Override
    public Path value5() {
        return getFileName();
    }

    @Override
    public Long value6() {
        return getLength();
    }

    @Override
    public String value7() {
        return getMimeType();
    }

    @Override
    public Integer value8() {
        return getNumberOfFail();
    }

    @Override
    public OffsetDateTime value9() {
        return getPubDate();
    }

    @Override
    public String value10() {
        return getTitle();
    }

    @Override
    public String value11() {
        return getUrl();
    }

    @Override
    public UUID value12() {
        return getCoverId();
    }

    @Override
    public UUID value13() {
        return getPodcastId();
    }

    @Override
    public String value14() {
        return getGuid();
    }

    @Override
    public ItemStatus value15() {
        return getStatus();
    }

    @Override
    public ItemRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public ItemRecord value2(OffsetDateTime value) {
        setCreationDate(value);
        return this;
    }

    @Override
    public ItemRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public ItemRecord value4(OffsetDateTime value) {
        setDownloadDate(value);
        return this;
    }

    @Override
    public ItemRecord value5(Path value) {
        setFileName(value);
        return this;
    }

    @Override
    public ItemRecord value6(Long value) {
        setLength(value);
        return this;
    }

    @Override
    public ItemRecord value7(String value) {
        setMimeType(value);
        return this;
    }

    @Override
    public ItemRecord value8(Integer value) {
        setNumberOfFail(value);
        return this;
    }

    @Override
    public ItemRecord value9(OffsetDateTime value) {
        setPubDate(value);
        return this;
    }

    @Override
    public ItemRecord value10(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public ItemRecord value11(String value) {
        setUrl(value);
        return this;
    }

    @Override
    public ItemRecord value12(UUID value) {
        setCoverId(value);
        return this;
    }

    @Override
    public ItemRecord value13(UUID value) {
        setPodcastId(value);
        return this;
    }

    @Override
    public ItemRecord value14(String value) {
        setGuid(value);
        return this;
    }

    @Override
    public ItemRecord value15(ItemStatus value) {
        setStatus(value);
        return this;
    }

    @Override
    public ItemRecord values(UUID value1, OffsetDateTime value2, String value3, OffsetDateTime value4, Path value5, Long value6, String value7, Integer value8, OffsetDateTime value9, String value10, String value11, UUID value12, UUID value13, String value14, ItemStatus value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ItemRecord
     */
    public ItemRecord() {
        super(Item.ITEM);
    }

    /**
     * Create a detached, initialised ItemRecord
     */
    public ItemRecord(UUID id, OffsetDateTime creationDate, String description, OffsetDateTime downloadDate, Path fileName, Long length, String mimeType, Integer numberOfFail, OffsetDateTime pubDate, String title, String url, UUID coverId, UUID podcastId, String guid, ItemStatus status) {
        super(Item.ITEM);

        setId(id);
        setCreationDate(creationDate);
        setDescription(description);
        setDownloadDate(downloadDate);
        setFileName(fileName);
        setLength(length);
        setMimeType(mimeType);
        setNumberOfFail(numberOfFail);
        setPubDate(pubDate);
        setTitle(title);
        setUrl(url);
        setCoverId(coverId);
        setPodcastId(podcastId);
        setGuid(guid);
        setStatus(status);
        resetChangedOnNotNull();
    }
}
