/*
 * This file is generated by jOOQ.
 */
package com.github.davinkevin.podcastserver.database.tables.records;


import com.github.davinkevin.podcastserver.database.tables.Playlist;

import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PlaylistRecord extends UpdatableRecordImpl<PlaylistRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.playlist.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.playlist.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.playlist.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.playlist.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlaylistRecord
     */
    public PlaylistRecord() {
        super(Playlist.PLAYLIST);
    }

    /**
     * Create a detached, initialised PlaylistRecord
     */
    public PlaylistRecord(UUID id, String name) {
        super(Playlist.PLAYLIST);

        setId(id);
        setName(name);
        resetChangedOnNotNull();
    }
}
