/*
 * This file is generated by jOOQ.
 */
package com.github.davinkevin.podcastserver.database.tables.records;


import com.github.davinkevin.podcastserver.database.tables.Playlist;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlaylistRecord extends UpdatableRecordImpl<PlaylistRecord> implements Record3<UUID, String, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.playlist.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.playlist.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.playlist.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.playlist.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.playlist.cover_id</code>.
     */
    public void setCoverId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.playlist.cover_id</code>.
     */
    public UUID getCoverId() {
        return (UUID) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, String, UUID> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<UUID, String, UUID> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Playlist.PLAYLIST.ID;
    }

    @Override
    public Field<String> field2() {
        return Playlist.PLAYLIST.NAME;
    }

    @Override
    public Field<UUID> field3() {
        return Playlist.PLAYLIST.COVER_ID;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public UUID component3() {
        return getCoverId();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public UUID value3() {
        return getCoverId();
    }

    @Override
    public PlaylistRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public PlaylistRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public PlaylistRecord value3(UUID value) {
        setCoverId(value);
        return this;
    }

    @Override
    public PlaylistRecord values(UUID value1, String value2, UUID value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlaylistRecord
     */
    public PlaylistRecord() {
        super(Playlist.PLAYLIST);
    }

    /**
     * Create a detached, initialised PlaylistRecord
     */
    public PlaylistRecord(UUID id, String name, UUID coverId) {
        super(Playlist.PLAYLIST);

        setId(id);
        setName(name);
        setCoverId(coverId);
        resetChangedOnNotNull();
    }
}
