/*
 * This file is generated by jOOQ.
 */
package com.github.davinkevin.podcastserver.database.enums;


import com.github.davinkevin.podcastserver.database.Public;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum ItemStatus implements EnumType {

    NOT_DOWNLOADED("NOT_DOWNLOADED"),

    STARTED("STARTED"),

    PAUSED("PAUSED"),

    DELETED("DELETED"),

    STOPPED("STOPPED"),

    FAILED("FAILED"),

    FINISH("FINISH");

    private final String literal;

    private ItemStatus(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "item_status";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static ItemStatus lookupLiteral(String literal) {
        return EnumType.lookupLiteral(ItemStatus.class, literal);
    }
}
