apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: frontend
spec:
  rules:
    - matches:
        - path:
            value: "/v2"
      backendRefs:
        - name: ui-v2
          port: 8080
    - matches:
        - path:
            value: "/"
      backendRefs:
        - name: ui-v1
          port: 8080
