/*
 * This file is generated by jOOQ.
 */
package com.github.davinkevin.podcastserver.database.tables;


import com.github.davinkevin.podcastserver.database.Keys;
import com.github.davinkevin.podcastserver.database.Public;
import com.github.davinkevin.podcastserver.database.tables.records.ApplicationSettingsRecord;

import java.time.OffsetDateTime;
import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ApplicationSettings extends TableImpl<ApplicationSettingsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.application_settings</code>
     */
    public static final ApplicationSettings APPLICATION_SETTINGS = new ApplicationSettings();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ApplicationSettingsRecord> getRecordType() {
        return ApplicationSettingsRecord.class;
    }

    /**
     * The column <code>public.application_settings.id</code>.
     */
    public final TableField<ApplicationSettingsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("uuidv7()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.application_settings.created_at</code>.
     */
    public final TableField<ApplicationSettingsRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.application_settings.concurrent_download</code>.
     */
    public final TableField<ApplicationSettingsRecord, Integer> CONCURRENT_DOWNLOAD = createField(DSL.name("concurrent_download"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("3"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.application_settings.number_of_try</code>.
     */
    public final TableField<ApplicationSettingsRecord, Integer> NUMBER_OF_TRY = createField(DSL.name("number_of_try"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("10"), SQLDataType.INTEGER)), this, "");

    /**
     * The column
     * <code>public.application_settings.number_of_day_to_download</code>.
     */
    public final TableField<ApplicationSettingsRecord, Long> NUMBER_OF_DAY_TO_DOWNLOAD = createField(DSL.name("number_of_day_to_download"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("30"), SQLDataType.BIGINT)), this, "");

    /**
     * The column
     * <code>public.application_settings.number_of_day_to_save_cover</code>.
     */
    public final TableField<ApplicationSettingsRecord, Long> NUMBER_OF_DAY_TO_SAVE_COVER = createField(DSL.name("number_of_day_to_save_cover"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("365"), SQLDataType.BIGINT)), this, "");

    private ApplicationSettings(Name alias, Table<ApplicationSettingsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ApplicationSettings(Name alias, Table<ApplicationSettingsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.application_settings</code> table
     * reference
     */
    public ApplicationSettings(String alias) {
        this(DSL.name(alias), APPLICATION_SETTINGS);
    }

    /**
     * Create an aliased <code>public.application_settings</code> table
     * reference
     */
    public ApplicationSettings(Name alias) {
        this(alias, APPLICATION_SETTINGS);
    }

    /**
     * Create a <code>public.application_settings</code> table reference
     */
    public ApplicationSettings() {
        this(DSL.name("application_settings"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<ApplicationSettingsRecord> getPrimaryKey() {
        return Keys.APPLICATION_SETTINGS_PKEY;
    }

    @Override
    public ApplicationSettings as(String alias) {
        return new ApplicationSettings(DSL.name(alias), this);
    }

    @Override
    public ApplicationSettings as(Name alias) {
        return new ApplicationSettings(alias, this);
    }

    @Override
    public ApplicationSettings as(Table<?> alias) {
        return new ApplicationSettings(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ApplicationSettings rename(String name) {
        return new ApplicationSettings(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ApplicationSettings rename(Name name) {
        return new ApplicationSettings(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ApplicationSettings rename(Table<?> name) {
        return new ApplicationSettings(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ApplicationSettings where(Condition condition) {
        return new ApplicationSettings(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ApplicationSettings where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ApplicationSettings where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ApplicationSettings where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ApplicationSettings where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ApplicationSettings where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ApplicationSettings where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ApplicationSettings where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ApplicationSettings whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ApplicationSettings whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
