/*
 * This file is generated by jOOQ.
 */
package com.github.davinkevin.podcastserver.database.tables;


import com.github.davinkevin.podcastserver.database.Indexes;
import com.github.davinkevin.podcastserver.database.Keys;
import com.github.davinkevin.podcastserver.database.Public;
import com.github.davinkevin.podcastserver.database.enums.ItemStatus;
import com.github.davinkevin.podcastserver.database.tables.Cover.CoverPath;
import com.github.davinkevin.podcastserver.database.tables.DownloadingItem.DownloadingItemPath;
import com.github.davinkevin.podcastserver.database.tables.Podcast.PodcastPath;
import com.github.davinkevin.podcastserver.database.tables.WatchList.WatchListPath;
import com.github.davinkevin.podcastserver.database.tables.WatchListItems.WatchListItemsPath;
import com.github.davinkevin.podcastserver.database.tables.records.ItemRecord;

import java.nio.file.Path;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Converter;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Item extends TableImpl<ItemRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.item</code>
     */
    public static final Item ITEM = new Item();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ItemRecord> getRecordType() {
        return ItemRecord.class;
    }

    /**
     * The column <code>public.item.id</code>.
     */
    public final TableField<ItemRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.item.creation_date</code>.
     */
    public final TableField<ItemRecord, OffsetDateTime> CREATION_DATE = createField(DSL.name("creation_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.item.description</code>.
     */
    public final TableField<ItemRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.item.download_date</code>.
     */
    public final TableField<ItemRecord, OffsetDateTime> DOWNLOAD_DATE = createField(DSL.name("download_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.item.file_name</code>.
     */
    public final TableField<ItemRecord, Path> FILE_NAME = createField(DSL.name("file_name"), SQLDataType.VARCHAR(65535), this, "", Converter.ofNullable(String.class, Path.class, Path::of, Path::toString));

    /**
     * The column <code>public.item.length</code>.
     */
    public final TableField<ItemRecord, Long> LENGTH = createField(DSL.name("length"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.item.mime_type</code>.
     */
    public final TableField<ItemRecord, String> MIME_TYPE = createField(DSL.name("mime_type"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.item.number_of_fail</code>.
     */
    public final TableField<ItemRecord, Integer> NUMBER_OF_FAIL = createField(DSL.name("number_of_fail"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.item.pub_date</code>.
     */
    public final TableField<ItemRecord, OffsetDateTime> PUB_DATE = createField(DSL.name("pub_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.item.title</code>.
     */
    public final TableField<ItemRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(65535).nullable(false), this, "");

    /**
     * The column <code>public.item.url</code>.
     */
    public final TableField<ItemRecord, String> URL = createField(DSL.name("url"), SQLDataType.VARCHAR(65535), this, "");

    /**
     * The column <code>public.item.cover_id</code>.
     */
    public final TableField<ItemRecord, UUID> COVER_ID = createField(DSL.name("cover_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.item.podcast_id</code>.
     */
    public final TableField<ItemRecord, UUID> PODCAST_ID = createField(DSL.name("podcast_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.item.guid</code>.
     */
    public final TableField<ItemRecord, String> GUID = createField(DSL.name("guid"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.item.status</code>.
     */
    public final TableField<ItemRecord, ItemStatus> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR.nullable(false).defaultValue(DSL.field(DSL.raw("'NOT_DOWNLOADED'::item_status"), SQLDataType.VARCHAR)).asEnumDataType(ItemStatus.class), this, "");

    private Item(Name alias, Table<ItemRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Item(Name alias, Table<ItemRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.item</code> table reference
     */
    public Item(String alias) {
        this(DSL.name(alias), ITEM);
    }

    /**
     * Create an aliased <code>public.item</code> table reference
     */
    public Item(Name alias) {
        this(alias, ITEM);
    }

    /**
     * Create a <code>public.item</code> table reference
     */
    public Item() {
        this(DSL.name("item"), null);
    }

    public <O extends Record> Item(Table<O> path, ForeignKey<O, ItemRecord> childPath, InverseForeignKey<O, ItemRecord> parentPath) {
        super(path, childPath, parentPath, ITEM);
    }

    /**
     * A subtype implementing {@link org.jooq.Path} for simplified path-based
     * joins.
     */
    public static class ItemPath extends Item implements org.jooq.Path<ItemRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ItemPath(Table<O> path, ForeignKey<O, ItemRecord> childPath, InverseForeignKey<O, ItemRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ItemPath(Name alias, Table<ItemRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ItemPath as(String alias) {
            return new ItemPath(DSL.name(alias), this);
        }

        @Override
        public ItemPath as(Name alias) {
            return new ItemPath(alias, this);
        }

        @Override
        public ItemPath as(Table<?> alias) {
            return new ItemPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ITEM_DOWNLOAD_DATE_ASC, Indexes.ITEM_DOWNLOAD_DATE_DESC, Indexes.ITEM_PUB_DATE_ASC, Indexes.ITEM_PUB_DATE_DESC, Indexes.ITEM_TITLE);
    }

    @Override
    public UniqueKey<ItemRecord> getPrimaryKey() {
        return Keys.ITEM_PKEY;
    }

    @Override
    public List<UniqueKey<ItemRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.ITEM_WITH_GUID_IS_UNIQUE_IN_PODCAST);
    }

    @Override
    public List<ForeignKey<ItemRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ITEM__ITEM_COVER_ID_FKEY, Keys.ITEM__ITEM_PODCAST_ID_FKEY);
    }

    private transient CoverPath _cover;

    /**
     * Get the implicit join path to the <code>public.cover</code> table.
     */
    public CoverPath cover() {
        if (_cover == null)
            _cover = new CoverPath(this, Keys.ITEM__ITEM_COVER_ID_FKEY, null);

        return _cover;
    }

    private transient PodcastPath _podcast;

    /**
     * Get the implicit join path to the <code>public.podcast</code> table.
     */
    public PodcastPath podcast() {
        if (_podcast == null)
            _podcast = new PodcastPath(this, Keys.ITEM__ITEM_PODCAST_ID_FKEY, null);

        return _podcast;
    }

    private transient DownloadingItemPath _downloadingItem;

    /**
     * Get the implicit to-many join path to the
     * <code>public.downloading_item</code> table
     */
    public DownloadingItemPath downloadingItem() {
        if (_downloadingItem == null)
            _downloadingItem = new DownloadingItemPath(this, null, Keys.DOWNLOADING_ITEM__DOWNLOADING_ITEM_ITEM_ID_FKEY.getInverseKey());

        return _downloadingItem;
    }

    private transient WatchListItemsPath _watchListItems;

    /**
     * Get the implicit to-many join path to the
     * <code>public.watch_list_items</code> table
     */
    public WatchListItemsPath watchListItems() {
        if (_watchListItems == null)
            _watchListItems = new WatchListItemsPath(this, null, Keys.WATCH_LIST_ITEMS__WATCH_LIST_ITEMS_ITEMS_ID_FKEY.getInverseKey());

        return _watchListItems;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.watch_list</code> table
     */
    public WatchListPath watchList() {
        return watchListItems().watchList();
    }

    @Override
    public List<Check<ItemRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("item_mime_type_not_empty"), "((((mime_type)::text <> ''::text) AND ((mime_type)::text ~~ '%/%'::text)))", true)
        );
    }

    @Override
    public Item as(String alias) {
        return new Item(DSL.name(alias), this);
    }

    @Override
    public Item as(Name alias) {
        return new Item(alias, this);
    }

    @Override
    public Item as(Table<?> alias) {
        return new Item(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Item rename(String name) {
        return new Item(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Item rename(Name name) {
        return new Item(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Item rename(Table<?> name) {
        return new Item(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Item where(Condition condition) {
        return new Item(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Item where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Item where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Item where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Item where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Item where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Item where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Item where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Item whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Item whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
