/*
 * This file is generated by jOOQ.
 */
package com.github.davinkevin.podcastserver.database.tables;


import com.github.davinkevin.podcastserver.database.Keys;
import com.github.davinkevin.podcastserver.database.Public;
import com.github.davinkevin.podcastserver.database.tables.Item.ItemPath;
import com.github.davinkevin.podcastserver.database.tables.Playlist.PlaylistPath;
import com.github.davinkevin.podcastserver.database.tables.records.PlaylistItemsRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PlaylistItems extends TableImpl<PlaylistItemsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.playlist_items</code>
     */
    public static final PlaylistItems PLAYLIST_ITEMS = new PlaylistItems();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PlaylistItemsRecord> getRecordType() {
        return PlaylistItemsRecord.class;
    }

    /**
     * The column <code>public.playlist_items.playlists_id</code>.
     */
    public final TableField<PlaylistItemsRecord, UUID> PLAYLISTS_ID = createField(DSL.name("playlists_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.playlist_items.items_id</code>.
     */
    public final TableField<PlaylistItemsRecord, UUID> ITEMS_ID = createField(DSL.name("items_id"), SQLDataType.UUID.nullable(false), this, "");

    private PlaylistItems(Name alias, Table<PlaylistItemsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PlaylistItems(Name alias, Table<PlaylistItemsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.playlist_items</code> table reference
     */
    public PlaylistItems(String alias) {
        this(DSL.name(alias), PLAYLIST_ITEMS);
    }

    /**
     * Create an aliased <code>public.playlist_items</code> table reference
     */
    public PlaylistItems(Name alias) {
        this(alias, PLAYLIST_ITEMS);
    }

    /**
     * Create a <code>public.playlist_items</code> table reference
     */
    public PlaylistItems() {
        this(DSL.name("playlist_items"), null);
    }

    public <O extends Record> PlaylistItems(Table<O> path, ForeignKey<O, PlaylistItemsRecord> childPath, InverseForeignKey<O, PlaylistItemsRecord> parentPath) {
        super(path, childPath, parentPath, PLAYLIST_ITEMS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PlaylistItemsPath extends PlaylistItems implements Path<PlaylistItemsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PlaylistItemsPath(Table<O> path, ForeignKey<O, PlaylistItemsRecord> childPath, InverseForeignKey<O, PlaylistItemsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PlaylistItemsPath(Name alias, Table<PlaylistItemsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PlaylistItemsPath as(String alias) {
            return new PlaylistItemsPath(DSL.name(alias), this);
        }

        @Override
        public PlaylistItemsPath as(Name alias) {
            return new PlaylistItemsPath(alias, this);
        }

        @Override
        public PlaylistItemsPath as(Table<?> alias) {
            return new PlaylistItemsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<PlaylistItemsRecord> getPrimaryKey() {
        return Keys.PLAYLIST_ITEMS_PKEY;
    }

    @Override
    public List<ForeignKey<PlaylistItemsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PLAYLIST_ITEMS__PLAYLIST_ITEMS_PLAYLISTS_ID_FKEY, Keys.PLAYLIST_ITEMS__PLAYLIST_ITEMS_ITEMS_ID_FKEY);
    }

    private transient PlaylistPath _playlist;

    /**
     * Get the implicit join path to the <code>public.playlist</code> table.
     */
    public PlaylistPath playlist() {
        if (_playlist == null)
            _playlist = new PlaylistPath(this, Keys.PLAYLIST_ITEMS__PLAYLIST_ITEMS_PLAYLISTS_ID_FKEY, null);

        return _playlist;
    }

    private transient ItemPath _item;

    /**
     * Get the implicit join path to the <code>public.item</code> table.
     */
    public ItemPath item() {
        if (_item == null)
            _item = new ItemPath(this, Keys.PLAYLIST_ITEMS__PLAYLIST_ITEMS_ITEMS_ID_FKEY, null);

        return _item;
    }

    @Override
    public PlaylistItems as(String alias) {
        return new PlaylistItems(DSL.name(alias), this);
    }

    @Override
    public PlaylistItems as(Name alias) {
        return new PlaylistItems(alias, this);
    }

    @Override
    public PlaylistItems as(Table<?> alias) {
        return new PlaylistItems(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PlaylistItems rename(String name) {
        return new PlaylistItems(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PlaylistItems rename(Name name) {
        return new PlaylistItems(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PlaylistItems rename(Table<?> name) {
        return new PlaylistItems(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlaylistItems where(Condition condition) {
        return new PlaylistItems(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlaylistItems where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlaylistItems where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlaylistItems where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlaylistItems where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlaylistItems where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlaylistItems where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PlaylistItems where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlaylistItems whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PlaylistItems whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
