/*
 * This file is generated by jOOQ.
 */
package com.github.davinkevin.podcastserver.database.tables;


import com.github.davinkevin.podcastserver.database.Keys;
import com.github.davinkevin.podcastserver.database.Public;
import com.github.davinkevin.podcastserver.database.tables.records.PlaylistRecord;

import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Playlist extends TableImpl<PlaylistRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.playlist</code>
     */
    public static final Playlist PLAYLIST = new Playlist();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PlaylistRecord> getRecordType() {
        return PlaylistRecord.class;
    }

    /**
     * The column <code>public.playlist.id</code>.
     */
    public final TableField<PlaylistRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.playlist.name</code>.
     */
    public final TableField<PlaylistRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.playlist.cover_id</code>.
     */
    public final TableField<PlaylistRecord, UUID> COVER_ID = createField(DSL.name("cover_id"), SQLDataType.UUID.nullable(false), this, "");

    private Playlist(Name alias, Table<PlaylistRecord> aliased) {
        this(alias, aliased, null);
    }

    private Playlist(Name alias, Table<PlaylistRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.playlist</code> table reference
     */
    public Playlist(String alias) {
        this(DSL.name(alias), PLAYLIST);
    }

    /**
     * Create an aliased <code>public.playlist</code> table reference
     */
    public Playlist(Name alias) {
        this(alias, PLAYLIST);
    }

    /**
     * Create a <code>public.playlist</code> table reference
     */
    public Playlist() {
        this(DSL.name("playlist"), null);
    }

    public <O extends Record> Playlist(Table<O> child, ForeignKey<O, PlaylistRecord> key) {
        super(child, key, PLAYLIST);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<PlaylistRecord> getPrimaryKey() {
        return Keys.PLAYLIST_PKEY;
    }

    @Override
    public List<UniqueKey<PlaylistRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.PLAYLIST_NAME_KEY);
    }

    @Override
    public List<ForeignKey<PlaylistRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PLAYLIST__PLAYLIST_COVER_ID_FK);
    }

    private transient Cover _cover;

    /**
     * Get the implicit join path to the <code>public.cover</code> table.
     */
    public Cover cover() {
        if (_cover == null)
            _cover = new Cover(this, Keys.PLAYLIST__PLAYLIST_COVER_ID_FK);

        return _cover;
    }

    @Override
    public Playlist as(String alias) {
        return new Playlist(DSL.name(alias), this);
    }

    @Override
    public Playlist as(Name alias) {
        return new Playlist(alias, this);
    }

    @Override
    public Playlist as(Table<?> alias) {
        return new Playlist(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Playlist rename(String name) {
        return new Playlist(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Playlist rename(Name name) {
        return new Playlist(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Playlist rename(Table<?> name) {
        return new Playlist(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, String, UUID> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super UUID, ? super String, ? super UUID, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super UUID, ? super String, ? super UUID, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
