/*
 * This file is generated by jOOQ.
 */
package com.github.davinkevin.podcastserver.database.tables;


import com.github.davinkevin.podcastserver.database.Keys;
import com.github.davinkevin.podcastserver.database.Public;
import com.github.davinkevin.podcastserver.database.tables.Item.ItemPath;
import com.github.davinkevin.podcastserver.database.tables.PlaylistItems.PlaylistItemsPath;
import com.github.davinkevin.podcastserver.database.tables.records.PlaylistRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Playlist extends TableImpl<PlaylistRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.playlist</code>
     */
    public static final Playlist PLAYLIST = new Playlist();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PlaylistRecord> getRecordType() {
        return PlaylistRecord.class;
    }

    /**
     * The column <code>public.playlist.id</code>.
     */
    public final TableField<PlaylistRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.playlist.name</code>.
     */
    public final TableField<PlaylistRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255), this, "");

    private Playlist(Name alias, Table<PlaylistRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Playlist(Name alias, Table<PlaylistRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.playlist</code> table reference
     */
    public Playlist(String alias) {
        this(DSL.name(alias), PLAYLIST);
    }

    /**
     * Create an aliased <code>public.playlist</code> table reference
     */
    public Playlist(Name alias) {
        this(alias, PLAYLIST);
    }

    /**
     * Create a <code>public.playlist</code> table reference
     */
    public Playlist() {
        this(DSL.name("playlist"), null);
    }

    public <O extends Record> Playlist(Table<O> path, ForeignKey<O, PlaylistRecord> childPath, InverseForeignKey<O, PlaylistRecord> parentPath) {
        super(path, childPath, parentPath, PLAYLIST);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PlaylistPath extends Playlist implements Path<PlaylistRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PlaylistPath(Table<O> path, ForeignKey<O, PlaylistRecord> childPath, InverseForeignKey<O, PlaylistRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PlaylistPath(Name alias, Table<PlaylistRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PlaylistPath as(String alias) {
            return new PlaylistPath(DSL.name(alias), this);
        }

        @Override
        public PlaylistPath as(Name alias) {
            return new PlaylistPath(alias, this);
        }

        @Override
        public PlaylistPath as(Table<?> alias) {
            return new PlaylistPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<PlaylistRecord> getPrimaryKey() {
        return Keys.PLAYLIST_PKEY;
    }

    @Override
    public List<UniqueKey<PlaylistRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.PLAYLIST_NAME_KEY);
    }

    private transient PlaylistItemsPath _playlistItems;

    /**
     * Get the implicit to-many join path to the
     * <code>public.playlist_items</code> table
     */
    public PlaylistItemsPath playlistItems() {
        if (_playlistItems == null)
            _playlistItems = new PlaylistItemsPath(this, null, Keys.PLAYLIST_ITEMS__PLAYLIST_ITEMS_PLAYLISTS_ID_FKEY.getInverseKey());

        return _playlistItems;
    }

    /**
     * Get the implicit many-to-many join path to the <code>public.item</code>
     * table
     */
    public ItemPath item() {
        return playlistItems().item();
    }

    @Override
    public Playlist as(String alias) {
        return new Playlist(DSL.name(alias), this);
    }

    @Override
    public Playlist as(Name alias) {
        return new Playlist(alias, this);
    }

    @Override
    public Playlist as(Table<?> alias) {
        return new Playlist(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Playlist rename(String name) {
        return new Playlist(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Playlist rename(Name name) {
        return new Playlist(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Playlist rename(Table<?> name) {
        return new Playlist(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Playlist where(Condition condition) {
        return new Playlist(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Playlist where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Playlist where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Playlist where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Playlist where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Playlist where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Playlist where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Playlist where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Playlist whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Playlist whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
